#!/bin/bash
set -euo pipefail

workspace="${WORKSPACE:-${GITHUB_WORKSPACE}}"

if [[ -z "${GH_TOKEN:-}" ]]; then
  echo "GH_TOKEN is required to create a GitHub release" >&2
  exit 1
fi

if command -v gh >/dev/null 2>&1; then
  gh --version
else
  sudo apt-get update
  sudo apt-get install -y gh
  gh --version
fi

build_dir="${workspace}/build"
if [[ ! -d "${build_dir}" ]]; then
  echo "Build directory not found: ${build_dir}" >&2
  exit 1
fi

machine="$(awk -F'"' '/^MACHINE[[:space:]]*\?*=|^MACHINE[[:space:]]*=/{print $2; exit}' "${build_dir}/conf/local.conf")"
if [[ -z "${machine}" ]]; then
  echo "Unable to determine MACHINE from ${build_dir}/conf/local.conf" >&2
  exit 1
fi

deploy_dir="${build_dir}/tmp/deploy/images/${machine}"
if [[ ! -d "${deploy_dir}" ]]; then
  echo "Deploy directory not found: ${deploy_dir}" >&2
  exit 1
fi

assets_dir="${workspace}/release-assets"
logs_dir="${build_dir}/release-logs"
mkdir -p "${assets_dir}" "${logs_dir}"

kernel=""
for candidate in bzImage Image zImage fitImage uImage vmlinuz bzImage.efi Image.efi; do
  if [[ -e "${deploy_dir}/${candidate}" ]]; then
    kernel="${deploy_dir}/${candidate}"
    break
  fi
done

if [[ -z "${kernel}" ]]; then
  kernel="$(find "${deploy_dir}" -maxdepth 1 \( -type f -o -type l \) \
    \( -name 'bzImage*' -o -name 'Image*' -o -name 'zImage*' -o -name 'fitImage*' -o -name 'uImage*' -o -name 'vmlinuz*' -o -name '*.efi' \) \
    | grep -Ev '[0-9]{8}' | head -n1 || true)"
fi

if [[ -z "${kernel}" ]]; then
  echo "Kernel image without date was not found in ${deploy_dir}" >&2
  exit 1
fi

rootfs="$(find "${deploy_dir}" -maxdepth 1 -type f -name "${BITBAKE_TARGET}-${machine}.rootfs.*" \
  ! -name '*.manifest' ! -name '*.testdata.json' ! -name '*.spdx*' ! -name '*.env' ! -name '*.bmap' \
  | sort | head -n1 || true)"

if [[ -z "${rootfs}" ]]; then
  rootfs="$(find "${deploy_dir}" -maxdepth 1 -type f -name "${BITBAKE_TARGET}-${machine}.*" \
    ! -name '*.manifest' ! -name '*.testdata.json' ! -name '*.spdx*' ! -name '*.env' ! -name '*.bmap' \
    ! -name '*.qemuboot.conf' ! -name '*.wic.bmap' \
    | grep -Ev '/(bzImage|Image|zImage|fitImage|uImage|vmlinuz)(\.|$)' | sort | head -n1 || true)"
fi

if [[ -z "${rootfs}" ]]; then
  echo "Root filesystem artifact was not found in ${deploy_dir}" >&2
  exit 1
fi

cp -L "${kernel}" "${assets_dir}/$(basename "${kernel}")"
cp -L "${rootfs}" "${assets_dir}/$(basename "${rootfs}")"

tar -C "${build_dir}" -czf "${assets_dir}/logs-${BITBAKE_TARGET}-${machine}.tar.gz" release-logs

cat > "${assets_dir}/release-notes.md" <<EOF
Draft release generated by workflow.

- Branch: ${GITHUB_REF_NAME}
- Target: ${BITBAKE_TARGET}
- Template: ${BITBAKE_TEMPLATE}
- Machine: ${machine}
- Run: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
EOF

title="${RELEASE_TITLE}"
if [[ -z "${title}" ]]; then
  title="${RELEASE_TAG} (${BITBAKE_TARGET} / ${BITBAKE_TEMPLATE})"
fi

gh release create "${RELEASE_TAG}" \
  --draft \
  --title "${title}" \
  --notes-file "${assets_dir}/release-notes.md" \
  "${assets_dir}"/*
