# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "project"
BBFILE_PATTERN_project = "^${LAYERDIR}/"
BBFILE_PRIORITY_project = "15"

LAYERDEPENDS_project = "core openembedded-layer security virtualization-layer sota"

LAYERSERIES_COMPAT_project = "scarthgap wrynose"
